package tiles;

import org.junit.Test;
import static org.junit.Assert.*;

public class TileMapTest {

    Tile[][] mapica = {
        {new Tile(TileType.Water), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},
        {new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt), new Tile(TileType.Dirt)},};

    @Test
    public void testGetTile() {
        TileMap instance = new TileMap(mapica);
        assertSame(mapica[0][0], instance.getTile(0, 0));
    }
}
